language: cpp
compiler:
  - gcc
os:
  - linux
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - ls -l
 - sudo cp -a libgtest_main.a libgtest.a /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"
before_script:
 - cd test/
 - cmake CMakeLists.txt
 - make
 - ls -l
script:
  - ./utest
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - brandl.matthaeus@gmail.com
  email:
    on_success: never
    on_failure: change
