language: cpp

compiler:
  - g++
os:
  - linux

addons:
  apt:
    sources:
#      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
#      - clang-3.7
      - g++-5
      - gcc-5
      - lcov

before_install:
    # Switch to gcc 5
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - sudo unlink /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov
  - g++ --version
  - gcov --version
    # Installing lcov
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - cd lcov-1.13/
  - sudo make install
  - cd ..
  - lcov --version
before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt
script:
  - cd "${TRAVIS_BUILD_DIR}"
  - make coverage
after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info 'test/*' --output-file coverage.info # filter out test
  - lcov --list coverage.info #debug info
    # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
branches:
  only:
    - master
    - develop
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
notifications:
  recipients:
    - brandl.matthaeus@gmail.com
  email:
    on_success: never
    on_failure: change
