language: cpp
compiler:
  - gcc-5
os:
  - linux
#env: GCC_VERSION=5 CPP=14 LIBCXX=Off
before_install:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
before_script:
  - cd test/
  - cmake CMakeLists.txt
script:
  - make
  - ./utest
branches:
  only:
    - master
    - develop
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-5
#      - g++-5
notifications:
  recipients:
    - brandl.matthaeus@gmail.com
  email:
    on_success: never
    on_failure: change
